root: "https://www.foxnews.com"
locator_strings:
- '[class*="title"]'
robots_txt_url: "https://www.foxnews.com/robots.txt"
ignore_robots_txt: false
max_pages: 500
max_workers: 5
save_path: "scraped_fox_headlines.json"
log_path: "scraper.log"
save_checkpoint: 50
headless: true
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
