root: "https://www.rnz.co.nz"
locator_strings:
- '[class="headline"]'
robots_txt_url: "https://www.rnz.co.nz/robots.txt"
ignore_robots_txt: false
max_pages: 500
max_workers: 20
save_path: "scraped_rnz_headlines.json"
log_path: "scraper.log"
save_checkpoint: 20
headless: true
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
